# Generated by Django 6.0.5 on 2026-07-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_telegram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discord_username',
        ),
    ]
