# Generated by Django 6.0.5 on 2026-07-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_discord_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
