# Generated by Django 6.0.5 on 2026-07-17 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_friends_friendrequest'),
        ('users', '0007_user_discord_username'),
    ]

    operations = [
    ]
