# Generated by Django 6.0.5 on 2026-07-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20260717_2000'),
        ('users', '0009_user_telegram_id_user_telegram_username_and_more'),
    ]

    operations = [
    ]
