# Generated by Django 6.0.5 on 2026-07-16 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='Момент першого accept — коли сесія стала live', null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='geofence_radius_m',
            field=models.PositiveIntegerField(default=40, help_text='Радіус (м) навколо point, при вході в який учасник вважається arrived'),
        ),
        migrations.AddField(
            model_name='activity',
            name='live_status',
            field=models.CharField(choices=[('pending', 'Очікує підтверджень'), ('active', 'Триває (live)'), ('completed', 'Завершено'), ('cancelled', 'Скасовано')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='invitation',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='responded_at',
            field=models.DateTimeField(blank=True, help_text='Коли to_user прийняв/відхилив запрошення', null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('accepted', 'Прийнято'), ('declined', 'Відхилено'), ('arrived', 'На місці'), ('left', 'Вийшов(ла)')], default='pending', max_length=10),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['live_status'], name='activities__live_st_b8fd85_idx'),
        ),
        migrations.AddIndex(
            model_name='invitation',
            index=models.Index(fields=['activity', 'status'], name='activities__activit_e48a02_idx'),
        ),
    ]
