# Generated by Django 6.0.5 on 2026-07-17 17:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_activity_activated_at_activity_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Тривалість кросу в секундах (для category=cross)', null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('sport', 'Спорт'), ('walk', 'Прогулянка'), ('hangout', 'Тусовка'), ('cross', 'Крос')], max_length=20),
        ),
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Порядок проходження (1, 2, 3 …)')),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('radius_m', models.PositiveIntegerField(default=30, help_text='Радіус (м) навколо чекпоїнту для вважання його пройденим')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='activities.activity')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_at', models.DateTimeField(auto_now_add=True)),
                ('checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passes', to='activities.checkpoint')),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passed_checkpoints', to='activities.invitation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='checkpoint',
            constraint=models.UniqueConstraint(fields=('activity', 'order'), name='unique_checkpoint_order_per_activity'),
        ),
        migrations.AddConstraint(
            model_name='participantcheckpoint',
            constraint=models.UniqueConstraint(fields=('invitation', 'checkpoint'), name='unique_invitation_checkpoint'),
        ),
    ]
