# Generated by Django 6.0.5 on 2026-07-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activity_duration_seconds_alter_activity_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_friends_only',
            field=models.BooleanField(default=False, help_text='Якщо True — зона видна тільки друзям творця'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('sport', 'Спорт'), ('walk', 'Прогулянка'), ('hangout', 'Тусовка'), ('cross', 'Крос'), ('zone', 'Ігрова зона')], max_length=20),
        ),
    ]
