# Generated by Django 6.0.5 on 2026-07-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_add_zone_category_and_friends_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('sport', 'Спорт'), ('walk', 'Прогулянка'), ('hangout', 'Тусовка'), ('cross', 'Крос'), ('zone', 'Ігрова зона'), ('quest', 'Квест')], max_length=20),
        ),
    ]
