# Generated by Django 6.0.5 on 2026-07-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_add_hiddenactivity'),
        ('activities', '0006_alter_activity_category'),
    ]

    operations = [
    ]
